version: '3'
services:
  express:
    image: desafio-magalu-backend
    build:
        context: .
    ports:
        - "3080:3080"
    container_name: desafio-magalu-backend-container
    volumes:
        - ./:/usr/src/desafio-magalu-backend
        - /usr/src/desafio-magalu-backend/node_modules
        - /usr/src/desafio-magalu-backend/build